apiVersion: v1
kind: Service
metadata:
  name: {{ include "garage.fullname" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.s3Api }}
      targetPort: s3-api
      protocol: TCP
      name: s3-api
    - port: {{ .Values.service.ports.s3Web }}
      targetPort: s3-web
      protocol: TCP
      name: s3-web
    - port: {{ .Values.service.ports.rpc }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.ports.admin }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}
{{- if .Values.monitoring.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "garage.fullname" . }}-metrics
  labels:
    {{- include "garage.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3903
      targetPort: 3903
      protocol: TCP
      name: metrics
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}
{{- end }}